
# Tree
Tree.hash=fade($Component.borderColor,10%)
Tree.paintLines=true
Tree.rendererMargins=4,5,4,7
Tree.showDefaultIcons=true
Tree.showsRootHandles=true
Tree.leafIcon=null
Tree.rightChildIndent=5
Tree.selectionBorderColor=null
Tree.wideCellRenderer=true

[style]Tree.menu=\
  selectionArc:8;\
  wideSelection:true;\
  background:$Panel.background;\
  [dark]selectionBackground:tint(@background,8%);\
  [light]selectionBackground:shade(@background,8%);\
  selectionInactiveBackground:$Tree.background;\
  selectionForeground:$Tree.foreground;\
  selectionInactiveForeground:$Tree.foreground;